"""HL7 FHIR Release 4 (R4) interoperability mapper.

Converts MedGuard internal clinical models into standard FHIR R4 resources:
- MedicationRequest (proposal intent for prescription items)
- Observation (vitals and patient-reported monitoring indicators)
- RiskAssessment & Flag (triage ESI and drug interaction warnings)
- Bundle (collection export)
"""

from __future__ import annotations

from time import time
from typing import Any
from uuid import uuid4


def to_fhir_patient_reference(patient_ref: str) -> dict[str, str]:
    return {"reference": f"Patient/{patient_ref}", "type": "Patient"}


def to_fhir_medication_request(
    *,
    patient_ref: str,
    medication_name: str,
    active_ingredient: str | None = None,
    strength: str | None = None,
    dosage_form: str | None = None,
    route: str = "oral",
    instructions: str | None = None,
    duration_days: int | None = None,
    requester_ref: str = "Practitioner/attending-physician",
) -> dict[str, Any]:
    """Maps extracted or prescribed medication to a FHIR R4 MedicationRequest.

    Note: intent is strictly 'proposal' because AI services cannot issue binding prescriptions.
    """
    return {
        "resourceType": "MedicationRequest",
        "id": f"mr-{uuid4().hex[:12]}",
        "status": "draft",
        "intent": "proposal",
        "subject": to_fhir_patient_reference(patient_ref),
        "medicationCodeableConcept": {
            "text": medication_name,
            "coding": [
                {
                    "system": "http://medguard.ai/pharmacy-catalog",
                    "code": active_ingredient or medication_name,
                    "display": medication_name,
                }
            ],
        },
        "dosageInstruction": [
            {
                "text": instructions or f"Take {dosage_form or 'unit'} orally as directed",
                "route": {
                    "coding": [
                        {
                            "system": "http://snomed.info/sct",
                            "code": "260548002" if route == "oral" else "generic-route",
                            "display": route,
                        }
                    ]
                },
                "timing": {
                    "repeat": {
                        "duration": duration_days or 5,
                        "durationUnit": "d",
                    }
                },
            }
        ],
        "note": [{"text": "Generated by MedGuard AI clinical safety service - PENDING_REVIEW"}],
    }


def to_fhir_observation(
    *,
    patient_ref: str,
    indicator: str,
    value: float,
    unit: str,
    recorded_at: str | None = None,
) -> dict[str, Any]:
    """Maps monitoring vitals to a FHIR R4 Observation resource."""
    return {
        "resourceType": "Observation",
        "id": f"obs-{uuid4().hex[:12]}",
        "status": "final",
        "category": [
            {
                "coding": [
                    {
                        "system": "http://terminology.hl7.org/CodeSystem/observation-category",
                        "code": "vital-signs",
                        "display": "Vital Signs",
                    }
                ]
            }
        ],
        "code": {
            "text": indicator,
            "coding": [
                {
                    "system": "http://medguard.ai/indicators",
                    "code": indicator.lower().replace(" ", "_"),
                    "display": indicator,
                }
            ],
        },
        "subject": to_fhir_patient_reference(patient_ref),
        "effectiveDateTime": recorded_at or "2026-09-07T00:00:00Z",
        "valueQuantity": {
            "value": value,
            "unit": unit,
            "system": "http://unitsofmeasure.org",
        },
    }


def to_fhir_risk_assessment(
    *,
    patient_ref: str,
    esi_level: int | None,
    urgency: str,
    red_flags: list[str],
    specialty: str | None = None,
) -> dict[str, Any]:
    """Maps triage decision and clinical warnings to a FHIR R4 RiskAssessment resource."""
    return {
        "resourceType": "RiskAssessment",
        "id": f"ra-{uuid4().hex[:12]}",
        "status": "final",
        "subject": to_fhir_patient_reference(patient_ref),
        "occurrenceDateTime": "2026-09-07T00:00:00Z",
        "prediction": [
            {
                "outcome": {
                    "text": f"Emergency Severity Index: ESI-{esi_level or 'Unspecified'} ({urgency})",
                    "coding": [
                        {
                            "system": "http://medguard.ai/esi-scale",
                            "code": f"ESI-{esi_level}" if esi_level else "ESI-UNKNOWN",
                            "display": urgency,
                        }
                    ],
                },
                "qualitativeRisk": {
                    "coding": [
                        {
                            "system": "http://terminology.hl7.org/CodeSystem/risk-probability",
                            "code": "high" if urgency == "EMERGENCY" else "moderate" if urgency == "URGENT" else "low",
                        }
                    ]
                },
                "rationale": "; ".join(red_flags) if red_flags else "No emergency red flags identified",
            }
        ],
        "note": [
            {"text": f"Recommended routing: {specialty or 'GENERAL'}"},
            {"text": "AI decision support suggestion only. Requires licensed clinical practitioner verification."},
        ],
    }


def to_fhir_bundle(resources: list[dict[str, Any]], bundle_type: str = "collection") -> dict[str, Any]:
    """Wraps multiple FHIR resources into a FHIR R4 Bundle."""
    return {
        "resourceType": "Bundle",
        "id": f"bundle-{uuid4().hex[:12]}",
        "type": bundle_type,
        "timestamp": "2026-09-07T00:00:00Z",
        "total": len(resources),
        "entry": [{"resource": r} for r in resources],
    }
